name: Build Go Code

on:
  push:
    branches:
      - main

jobs:
  golangci:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: stable

      - name: Build binary
        run: |
          go build -o main .